# 激活开发环境dev（关键）
spring:
  profiles:
    active: dev

# MybatisPlus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.saas.platform.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Knife4j接口文档
knife4j:
  enable: true
  settings:
    language: zh_CN

# 自定义JWT配置
jwt:
  secret: SaasPlatform2026SecretKey666888GuangZhouJavaSaaS
  expire: 7200000
  header: Authorization
  prefix: Bearer

# 安全鉴权开关
app:
  security-enabled: true