services:
  # MySQL8.0 适配M芯片ARM架构，移除platform
  mysql:
    image: mysql:8.0.36
    container_name: saas-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: saas_platform
      # 解决MySQL8时区、客户端加密兼容
      TZ: Asia/Shanghai
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    command:
      # 兼容旧数据库客户端
      --default-authentication-plugin=mysql_native_password

  # Redis7.0 增加密码
  redis:
    image: redis:7.0-alpine
    container_name: saas-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456
    volumes:
      - ./redis-data:/data
    restart: always

  # RabbitMQ 带持久化
  rabbitmq:
    image: rabbitmq:3-management
    container_name: saas-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    restart: always

  # MinIO 文件存储 持久化
  minio:
    image: minio/minio
    container_name: saas-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
      TZ: Asia/Shanghai
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    restart: always

  # XXL-JOB 调度中心
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: saas-xxl-job
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      TZ: Asia/Shanghai
    depends_on:
      - mysql
    restart: always